image: nikkoamiu/phoenix_framework:1.0

variables:
  POSTGRES_DB: my_wedding_test
  POSTGRES_USER: my_wedding_svc
  POSTGRES_PASSWORD: postgres
  MIX_ENV: test

stages:
  - build
  - test
  - release
  - verify
  - push image
  - deploy

compile:
  stage: build
  script:
    - make build
    - make assets
  artifacts:
    untracked: true

# Run Application Tests
test:
  stage: test
  dependencies:
    - compile
  services:
    - postgres:latest
  script:
    - mix test

coverage:
  stage: test
  dependencies:
    - compile
  services:
    - postgres:latest
  script:
    - mix coveralls

# Verify a release can be merged into master
mergability:
  stage: test
  image: debian:jessie
  before_script:
    - apt-get update && apt-get install git -y
    - git config --global user.email "admin@nikkomiu.com"
    - git config --global user.name "CI"
  script:
    - git checkout master
    - git merge $CI_BUILD_REF
  only:
    - develop

# Create the Release Artifacts
releasearaptor:
  stage: release
  script: MIX_ENV=prod make release
  artifacts:
    name: $CI_PROJECT_NAME
    paths:
      - rel/$CI_PROJECT_NAME/

# Build and Deploy Docker Image
containerize:
  stage: push image
  image: docker:latest
  dependencies:
    - releasearaptor
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_BUILD_REF_NAME .
    - docker push registry.gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_BUILD_REF_NAME

# Run Migrations and Deploy
migrate:
  stage: deploy
  dependencies:
    - releasearaptor
  before_script:
    - MIX_ENV=prod make build
    - chmod +x deploy/setup.sh deploy/migrate.sh
    - eval "$(deploy/setup.sh)"
  script:
    - deploy/migrate.sh
  only:
    - tags
    - master

deploy:
  stage: deploy
  image: debian:latest
  before_script:
    - apt-get update && apt-get install curl -y
    - chmod +x deploy/setup.sh deploy/trigger_build.sh
    - eval "$(deploy/setup.sh)"
  script:
    - deploy/trigger_build.sh
  only:
    - tags
    - master
