FROM elixir:1.3

MAINTAINER Nikko Miu <nikkoamiu@gmail.com>

# Install NGINX
RUN wget https://gist.githubusercontent.com/nikkomiu/cd15d615fc3390ebbd79e9d078458d10/raw/nginx_install.sh
RUN chmod +x ./nginx_install.sh
RUN ./nginx_install.sh 1.11.2

# Install NodeJS
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install nodejs -y

# Install SASS
RUN apt-get install ruby-full -y
RUN gem install sass

# Move NGINX config into place
COPY deploy/nginx.conf /etc/nginx/nginx.conf

# Copy dependency config
COPY mix.* /usr/app/
COPY package.json /usr/app
COPY bower.json /usr/app
COPY Makefile /usr/app
WORKDIR /usr/app

# Install dependencies
RUN make install
RUN make deps

# Copy app
COPY . /usr/app

# App ENV
ENV PORT=4000
ENV MIX_ENV=prod

# Build app release
RUN make release

WORKDIR /usr/app/rel/wedding_website

EXPOSE $PORT

CMD ["bin/wedding_website", "start"]
