kind: Service
apiVersion: v1
metadata:
  labels:
    role: database
    name: postgres
  name: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    name: postgres
