kind: Secret
apiVersion: v1
metadata:
  name: our-wedding-secret
type: Opaque
data:
  db-url: bXlzZWNyZXRzdHJpbmc=
  google-client-id: bXlzZWNyZXRzdHJpbmc=
  google-client-secret: bXlzZWNyZXRzdHJpbmc=
  recaptcha-key: bXlzZWNyZXRzdHJpbmc=
  recaptcha-secret: bXlzZWNyZXRzdHJpbmc=
  secret-key-base: bXlzZWNyZXRzdHJpbmc=
