kind: Service
apiVersion: v1
metadata:
  labels:
    app: our-wedding
    name: our-wedding-web
  name: our-wedding-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: nginx-insecure
    - port: 443
      targetPort: 443
      protocol: TCP
      name: nginx-secure
  selector:
    name: our-wedding-web
